#
#  //\\   OmenMon: Hardware Monitoring & Control Utility
# //  \\  Copyright © 2023 Piotr Szczepański * License: GPL3
#     //  https://omenmon.github.io/
#
# OmenMon Build Workflow
# Builds the application with the specified version data

name: "OmenMon Build"
run-name: "OmenMon Build by ${{ github.actor }}"

on:
  workflow_call:
    inputs:
      version_number:
        description: "Version number for the build, must consist of exactly three positive integers separated by dots"
        default: "0.0.0"
        required: false
        type: string
      version_word:
        description: "Version word indicating build type"
        default: "GitHub-C"
        required: false
        type: string

  workflow_dispatch:
    inputs:
      version_number:
        description: "Version number for the build, must consist of exactly three positive integers separated by dots"
        default: "0.0.0"
        required: false
        type: string
      version_word:
        description: "Version word indicating build type"
        default: "GitHub-D"
        required: false
        type: string

permissions:
  contents: read

jobs:
  Call-Bump-Build:
    name: "Call Bump"
    secrets: inherit
    uses: ./.github/workflows/build_bump.yml

  Build-OmenMon:
    name: "Build OmenMon"
    needs: Call-Bump-Build
    runs-on: windows-2022

    strategy:
      matrix:
        configuration: ["Release"]

    steps:
    - name: "Checkout OmenMon"
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: "Checkout OmenMon Resources"
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: ${{ vars.RESOURCES_DIR }}
        repository: ${{ vars.RESOURCES_REPO }}

    - name: "Set up Microsoft Build"
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        vs-version: "[17.7,)"

    - name: "Run Microsoft Build"
      working-directory: ${{ github.workspace }}
      run: >
        msbuild -m -noLogo
        -p:AssemblyVersion=${{inputs.version_number}}.${{vars.BUILD_NUMBER}}
        -p:AssemblyVersionWord=${{inputs.version_word}}
        -p:Configuration=${{matrix.configuration}}
        -t:Build ${{vars.SOLUTION_FILE}}

    - name: "Upload OmenMon"
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: "OmenMon"
        path: "Bin"
