#
#  //\\   OmenMon: Hardware Monitoring & Control Utility
# //  \\  Copyright © 2023 Piotr Szczepański * License: GPL3
#     //  https://omenmon.github.io/
#
# OmenMon Build Bump Workflow
# Bumps up the build number stored in a variable

name: "OmenMon Build Bump"
run-name: "OmenMon Build Bump by ${{ github.actor }}"

on: [workflow_call, workflow_dispatch]

permissions:
  actions: write

jobs:
  Bump-Build:
    name: "Bump up Build Number"
    runs-on: windows-2022

    steps:
    - name: "Increment and Store the Build Number"
      run: >
        echo "BUILD_NUMBER=$(${{ vars.BUILD_NUMBER }} + 1)" >> $env:GITHUB_ENV
      shell: pwsh


    - name: Get registration token
      id: getRegToken
      run: >
        curl
        -X POST
        -H "Accept: application/vnd.github.v3+json"
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
        https://api.github.com/repos/OmenMon/OmenMon/actions/runners/registration-token

    - name: "Call REST API"
      run: >
        curl -L
        -X PATCH
        -H "Accept: application/vnd.github+json"
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
        -H "X-GitHub-Api-Version: 2022-11-28"
        -d '{"name": "BUILD_NUMBER", "value": "${{ env.BUILD_NUMBER }}"}'
        https://api.github.com/repos/OmenMon/OmenMon/actions/variables/BUILD_NUMBER
